---
name: "AppwriteAuth"
guid: "1f51419e-8bc3-4fb6-868e-6e8a094d9707"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Appwrite-backed authentication for Jellyfin with admin invite/reset tools"
description: >
  AppwriteAuth delegates authentication to Appwrite while keeping all Jellyfin URLs unchanged.
  Includes admin tools to invite users and reset passwords via Appwrite Messaging or SMTP fallback,
  with clean, branded HTML emails. Supports email or username login with automatic user provisioning.
category: "Authentication"
owner: "ZachHandley"
artifacts:
- "Jellyfin.Plugin.Template.dll"
changelog: >
  changelog
