---
name: "AppwriteAuth"
guid: "1f51419e-8bc3-4fb6-868e-6e8a094d9707"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Appwrite-backed authentication for Jellyfin with admin invite/reset tools"
description: >
  AppwriteAuth delegates authentication to Appwrite while keeping all Jellyfin URLs unchanged.
  Includes admin tools to invite users and reset passwords via Appwrite Messaging or SMTP fallback,
  with clean, branded HTML emails. Supports email or username login with automatic user provisioning.
category: "Authentication"
owner: "ZachHandley"
artifacts:
- "Jellyfin.Plugin.AppwriteAuth.dll"
dependencies:
  - name: "Custom Tabs"
    guid: "fbacd0b6-fd46-4a05-b0a4-2045d6a135b0"
    version: ">=0.2.2.0"
changelog: >
  Initial release with Vue 3 admin interface:
  - Appwrite authentication integration with automatic user provisioning
  - Modern Vue 3 + TypeScript admin interface (155 KB gzipped)
  - Email provider support (SMTP or Appwrite Messaging)
  - Admin tools: Invite users, reset passwords, test email configuration
  - Customizable branding (logo, colors, email templates)
  - Dark mode support matching Jellyfin theme
  - Toast notifications for user feedback
  - Requires Custom Tabs plugin for navigation integration
